version: "3"

tasks:
  build:
    desc: Build the container image
    cmds:
      - docker compose up --force-recreate --build
  up:
    desc: Uo the irons
    cmds:
      - docker compose up
  shell:
    desc: hax0r
    cmds:
      - docker compose exec web env TERM=xterm-256color script -q -c "/bin/bash" /dev/null

  clean:
    desc: junk
    cmds:
      - "docker compose rm -f ||:"

  require:
    desc: composer require
    cmds:
      - php composer.phar require {{.CLI_ARGS}}

  nuke:
    cmds:
      - docker compose rm -v -f
      - docker image prune -a -f
      - docker volume prune -f

  update:
    desc: composer update
    cmds:
      - php composer.phar update {{.CLI_ARGS}}
      